service: aws-spa-shop

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

plugins:
  - serverless-finch
  - serverless-single-page-app-plugin

custom:
  client:
    bucketName: websitebucket-shop-sls
    distributionFolder: ./dist
    indexDocument: index.html
    errorDocument: index.html
  s3Bucket: ${self:custom.client.bucketName}

resources:
  Resources:
    OriginAccessIdentity:
      Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
      Properties:
        CloudFrontOriginAccessIdentityConfig:
          Comment: "SPA OAI"
    SPAS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.s3Bucket}
        AccessControl: BucketOwnerFullControl
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: index.html
    SPAS3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref SPAS3Bucket
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Action:
                - 's3:GetObject'
              Effect: Allow
              Principal:
                AWS: !Join
                  - ''
                  - - 'arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity'
                    - ' '
                    - !Ref OriginAccessIdentity
              Resource: !Join 
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref SPAS3Bucket
                  - /*
            - Action:
                - 's3:ListBucket'
              Effect: Allow
              Principal:
                AWS: !Join
                  - ''
                  - - 'arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity'
                    - ' '
                    - !Ref OriginAccessIdentity
              Resource: !Join 
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref SPAS3Bucket
    SPACloudFrontDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Origins:
            - DomainName: ${self:custom.s3Bucket}.s3.amazonaws.com
              Id: SPA
              S3OriginConfig:
                OriginAccessIdentity: !Join
                  - ''
                  - - origin-access-identity/cloudfront/
                    - !Ref OriginAccessIdentity
          Enabled: 'true'
          DefaultRootObject: index.html
          CustomErrorResponses:
            - ErrorCode: 404
              ResponseCode: 200
              ResponsePagePath: /index.html
          DefaultCacheBehavior:
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
            TargetOriginId: SPA
            ForwardedValues:
              QueryString: 'false'
              Cookies:
                Forward: none
            ViewerProtocolPolicy: redirect-to-https
          ViewerCertificate:
            CloudFrontDefaultCertificate: 'true'
  Outputs:
    WebAppCloudFrontDistributionOutput:
      Value:
        'Fn::GetAtt': [SPACloudFrontDistribution, DomainName]

