service: task-2

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-1
  lambdaHashingVersion: 20201221

plugins:
  - serverless-finch
custom:
  client:
    bucketName: task2-manual
    distributionFolder: build
