service: sls

frameworkVersion: "3"

plugins:
  - serverless-finch

provider:
  name: aws
  runtime: nodejs12.x
  # lambdaHashingVersion: 20201221

custom:
  client:
    bucketName: battiw-first-bucket
    distributionFolder: build
    indexDocument: index.html
    errorDocument: index.html
